=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::AreasApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AreasApi' do
  before do
    # run before each test
    @instance = Vouchery::AreasApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AreasApi' do
    it 'should create an instance of AreasApi' do
      expect(@instance).to be_instance_of(Vouchery::AreasApi)
    end
  end

  # unit tests for create_area
  # Create an area
  # @param [Hash] opts the optional parameters
  # @option opts [Area] :area 
  # @return [Area]
  describe 'create_area test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_area
  # Delete an area
  # @param id Area ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_area test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_area
  # Get an area
  # @param id Area ID
  # @param [Hash] opts the optional parameters
  # @return [Area]
  describe 'get_area test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_areas
  # Get all areas
  # @param [Hash] opts the optional parameters
  # @return [Array<Area>]
  describe 'get_areas test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_area
  # Update an area
  # @param id Area ID
  # @param [Hash] opts the optional parameters
  # @option opts [Area] :area 
  # @return [Area]
  describe 'update_area test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
