=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::BudgetRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BudgetRulesApi' do
  before do
    # run before each test
    @instance = Vouchery::BudgetRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BudgetRulesApi' do
    it 'should create an instance of BudgetRulesApi' do
      expect(@instance).to be_instance_of(Vouchery::BudgetRulesApi)
    end
  end

  # unit tests for create_budget_rule
  # Create a budget rule
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @option opts [BudgetRule] :budget_rule 
  # @return [BudgetRule]
  describe 'create_budget_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_budget_rule
  # Delete a rule
  # @param id Rule ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_budget_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_budget_rule
  # Get a budget rule
  # @param id Rule ID
  # @param [Hash] opts the optional parameters
  # @return [BudgetRule]
  describe 'get_budget_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_budget_rules
  # Get all budget rules for a campaign
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [Array<BudgetRule>]
  describe 'get_budget_rules test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_budget_rule
  # Update a budget rule
  # @param id Rule ID
  # @param [Hash] opts the optional parameters
  # @option opts [BudgetRule] :budget_rule 
  # @return [BudgetRule]
  describe 'update_budget_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
