=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::CategoryRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CategoryRulesApi' do
  before do
    # run before each test
    @instance = Vouchery::CategoryRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoryRulesApi' do
    it 'should create an instance of CategoryRulesApi' do
      expect(@instance).to be_instance_of(Vouchery::CategoryRulesApi)
    end
  end

  # unit tests for create_category_rule
  # Create a category rule
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @option opts [CategoryRule] :category_rule 
  # @return [CategoryRule]
  describe 'create_category_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_category_rule
  # Delete a category rule
  # @param id Rule ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_category_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_category_rule
  # Get a category rule
  # @param id Rule ID
  # @param [Hash] opts the optional parameters
  # @return [CategoryRule]
  describe 'get_category_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_category_rules
  # Get all category rules for a campaign
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [Array<CategoryRule>]
  describe 'get_category_rules test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_category_rule
  # Update a category rule
  # @param id Rule ID
  # @param [Hash] opts the optional parameters
  # @option opts [CategoryRule] :category_rule 
  # @return [CategoryRule]
  describe 'update_category_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
