=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::CustomersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @instance = Vouchery::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@instance).to be_instance_of(Vouchery::CustomersApi)
    end
  end

  # unit tests for assign_voucher_to_customer
  # Assign vouchers to a customer
  # @param identifier Customer identifier
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject] :inline_object 
  # @return [Customer]
  describe 'assign_voucher_to_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_customer
  # Create a customer
  # @param [Hash] opts the optional parameters
  # @option opts [Customer] :customer 
  # @return [Customer]
  describe 'create_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_customer
  # Delete a customer
  # @param identifier Customer identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer
  # Get a customer
  # @param identifier Customer identifier
  # @param [Hash] opts the optional parameters
  # @return [Customer]
  describe 'get_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_redemptions
  # Get redemptions performed by a customer
  # @param identifier Customer identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<Redemption>]
  describe 'get_customer_redemptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_vouchers
  # Get vouchers assigned to a customer
  # @param identifier Customer identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<Voucher>]
  describe 'get_customer_vouchers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customers
  # Get all customers
  # @param [Hash] opts the optional parameters
  # @return [Array<Customer>]
  describe 'get_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
