=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::PerCustomerRuleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PerCustomerRuleApi' do
  before do
    # run before each test
    @instance = Vouchery::PerCustomerRuleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PerCustomerRuleApi' do
    it 'should create an instance of PerCustomerRuleApi' do
      expect(@instance).to be_instance_of(Vouchery::PerCustomerRuleApi)
    end
  end

  # unit tests for create_per_customer_rule
  # Create the per customer rule
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @option opts [PerCustomerRule] :per_customer_rule 
  # @return [PerCustomerRule]
  describe 'create_per_customer_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_per_customer_rule
  # Delete the per customer rule
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_per_customer_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_per_customer_rule
  # Get the per customer rule
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [PerCustomerRule]
  describe 'get_per_customer_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_per_customer_rule
  # Update the per customer rule
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @option opts [PerCustomerRule] :per_customer_rule 
  # @return [PerCustomerRule]
  describe 'update_per_customer_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
