=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::RedemptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RedemptionsApi' do
  before do
    # run before each test
    @instance = Vouchery::RedemptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedemptionsApi' do
    it 'should create an instance of RedemptionsApi' do
      expect(@instance).to be_instance_of(Vouchery::RedemptionsApi)
    end
  end

  # unit tests for confirm_redemption
  # Confirm a redemption
  # @param code Voucher code
  # @param transaction_id ID which identifies the transaction in customer system, e.g. order number, invoice number
  # @param [Hash] opts the optional parameters
  # @return [Redemption]
  describe 'confirm_redemption test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_redemption
  # Create a redemption
  # @param code Voucher code
  # @param [Hash] opts the optional parameters
  # @option opts [Redemption] :redemption 
  # @return [Redemption]
  describe 'create_redemption test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_redemption
  # Delete a redemption
  # @param code Voucher code
  # @param transaction_id ID which identifies the transaction in customer system, e.g. order number, invoice number
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_redemption test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_redemption
  # Get a redemption
  # @param code Voucher code
  # @param transaction_id ID which identifies the transaction in customer system, e.g. order number, invoice number
  # @param [Hash] opts the optional parameters
  # @return [Redemption]
  describe 'get_redemption test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_redemptions
  # Get all redemptions for a campaign
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [Array<Redemption>]
  describe 'get_redemptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
