=begin
#Vouchery API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::RewardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RewardsApi' do
  before do
    # run before each test
    @api_instance = Vouchery::RewardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RewardsApi' do
    it 'should create an instance of RewardsApi' do
      expect(@api_instance).to be_instance_of(Vouchery::RewardsApi)
    end
  end

  # unit tests for create_reward
  # Create a reward
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @option opts [Reward] :reward 
  # @return [Reward]
  describe 'create_reward test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_reward
  # Delete a reward
  # @param id Reward ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_reward test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_reward
  # Get a reward
  # @param id Reward ID
  # @param [Hash] opts the optional parameters
  # @return [Reward]
  describe 'get_reward test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_rewards
  # Get all rewards for a campaign
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [Array<Reward>]
  describe 'get_rewards test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_reward
  # Update a reward
  # @param id Reward ID
  # @param [Hash] opts the optional parameters
  # @option opts [Reward] :reward 
  # @return [Reward]
  describe 'update_reward test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
