=begin
#Vouchery API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Vouchery::TriggersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TriggersApi' do
  before do
    # run before each test
    @api_instance = Vouchery::TriggersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TriggersApi' do
    it 'should create an instance of TriggersApi' do
      expect(@api_instance).to be_instance_of(Vouchery::TriggersApi)
    end
  end

  # unit tests for create_trigger
  # Create a trigger
  # @param [Hash] opts the optional parameters
  # @option opts [Trigger] :trigger 
  # @return [Trigger]
  describe 'create_trigger test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
