=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'date'

module Vouchery
  class Batch
    # Should be generated vouchers be active?
    attr_accessor :active

    # How many unique vouchers to generate? Can be an number between 1 and 50 000.
    attr_accessor :size

    # What characters should the code include. Possible choices are digits, letters, and mixed.
    attr_accessor :code_type

    # How long should the random part of the code be? Valid values are between 2 and 10, depending on batch size.
    attr_accessor :random_part_length

    # A prefix is required for batch generated coupons. Needs to be unique within project.
    attr_accessor :prefix

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'active' => :'active',
        :'size' => :'size',
        :'code_type' => :'code_type',
        :'random_part_length' => :'random_part_length',
        :'prefix' => :'prefix'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'active' => :'BOOLEAN',
        :'size' => :'Float',
        :'code_type' => :'String',
        :'random_part_length' => :'Float',
        :'prefix' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.has_key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.has_key?(:'code_type')
        self.code_type = attributes[:'code_type']
      end

      if attributes.has_key?(:'random_part_length')
        self.random_part_length = attributes[:'random_part_length']
      end

      if attributes.has_key?(:'prefix')
        self.prefix = attributes[:'prefix']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @active.nil?
        invalid_properties.push('invalid value for "active", active cannot be nil.')
      end

      if @size.nil?
        invalid_properties.push('invalid value for "size", size cannot be nil.')
      end

      if @size > 50000
        invalid_properties.push('invalid value for "size", must be smaller than or equal to 50000.')
      end

      if @size < 1
        invalid_properties.push('invalid value for "size", must be greater than or equal to 1.')
      end

      if @code_type.nil?
        invalid_properties.push('invalid value for "code_type", code_type cannot be nil.')
      end

      if @random_part_length.nil?
        invalid_properties.push('invalid value for "random_part_length", random_part_length cannot be nil.')
      end

      if @random_part_length > 10
        invalid_properties.push('invalid value for "random_part_length", must be smaller than or equal to 10.')
      end

      if @random_part_length < 3
        invalid_properties.push('invalid value for "random_part_length", must be greater than or equal to 3.')
      end

      if @prefix.nil?
        invalid_properties.push('invalid value for "prefix", prefix cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @active.nil?
      return false if @size.nil?
      return false if @size > 50000
      return false if @size < 1
      return false if @code_type.nil?
      code_type_validator = EnumAttributeValidator.new('String', ['digits', 'letters', 'mixed'])
      return false unless code_type_validator.valid?(@code_type)
      return false if @random_part_length.nil?
      return false if @random_part_length > 10
      return false if @random_part_length < 3
      return false if @prefix.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] size Value to be assigned
    def size=(size)
      if size.nil?
        fail ArgumentError, 'size cannot be nil'
      end

      if size > 50000
        fail ArgumentError, 'invalid value for "size", must be smaller than or equal to 50000.'
      end

      if size < 1
        fail ArgumentError, 'invalid value for "size", must be greater than or equal to 1.'
      end

      @size = size
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] code_type Object to be assigned
    def code_type=(code_type)
      validator = EnumAttributeValidator.new('String', ['digits', 'letters', 'mixed'])
      unless validator.valid?(code_type)
        fail ArgumentError, 'invalid value for "code_type", must be one of #{validator.allowable_values}.'
      end
      @code_type = code_type
    end

    # Custom attribute writer method with validation
    # @param [Object] random_part_length Value to be assigned
    def random_part_length=(random_part_length)
      if random_part_length.nil?
        fail ArgumentError, 'random_part_length cannot be nil'
      end

      if random_part_length > 10
        fail ArgumentError, 'invalid value for "random_part_length", must be smaller than or equal to 10.'
      end

      if random_part_length < 3
        fail ArgumentError, 'invalid value for "random_part_length", must be greater than or equal to 3.'
      end

      @random_part_length = random_part_length
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          active == o.active &&
          size == o.size &&
          code_type == o.code_type &&
          random_part_length == o.random_part_length &&
          prefix == o.prefix
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [active, size, code_type, random_part_length, prefix].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Vouchery.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
