=begin
#Vouchery API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 1.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'date'

module Vouchery
  class Campaign
    attr_accessor :type

    attr_accessor :id

    attr_accessor :parent_id

    # Type of campaign.
    attr_accessor :campaign_type

    attr_accessor :status

    # The name of the campaign.
    attr_accessor :name

    attr_accessor :description

    # Text that can be displayed to the customer once the redemption is validated or confirmed.
    attr_accessor :customer_information

    # Determines what type of vouchers can be generated for campaign. Generic coupons (eg. SALE10) can be redeemed multiple times. Unique vouchers allow for greater control and better tracking of who and how is using your promotions.
    attr_accessor :voucher_type

    # The budget available for all discount campaigns grouped by this campaign.
    attr_accessor :max_total_budget

    # The maximum number of redemptions available across all discount campaigns grouped by this campaign.
    attr_accessor :max_redemptions

    attr_accessor :minimum_value

    attr_accessor :maximum_value

    # Discount type defines if a customer receive should receive a discount of 10% or $10 on their order.
    attr_accessor :discount_type

    attr_accessor :discount_value

    # Currency denominating monetary values in this campaign (USD, GBP, EUR, AUD)
    attr_accessor :currency

    # Currency symbol ($, £, €)
    attr_accessor :currency_symbol

    # Short reward title to be displayed to the customer (max. 40 characters)
    attr_accessor :reward_title

    # Automatically generated reward value description, e.g. \"10% off\", \"$5 off\"
    attr_accessor :reward_value

    # Short reward description to be displayed to the customer (max. 100 characters)
    attr_accessor :reward_description

    attr_accessor :team

    attr_accessor :channel

    attr_accessor :purpose

    attr_accessor :budget_code

    attr_accessor :medium

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'id' => :'id',
        :'parent_id' => :'parent_id',
        :'campaign_type' => :'campaign_type',
        :'status' => :'status',
        :'name' => :'name',
        :'description' => :'description',
        :'customer_information' => :'customer_information',
        :'voucher_type' => :'voucher_type',
        :'max_total_budget' => :'max_total_budget',
        :'max_redemptions' => :'max_redemptions',
        :'minimum_value' => :'minimum_value',
        :'maximum_value' => :'maximum_value',
        :'discount_type' => :'discount_type',
        :'discount_value' => :'discount_value',
        :'currency' => :'currency',
        :'currency_symbol' => :'currency_symbol',
        :'reward_title' => :'reward_title',
        :'reward_value' => :'reward_value',
        :'reward_description' => :'reward_description',
        :'team' => :'team',
        :'channel' => :'channel',
        :'purpose' => :'purpose',
        :'budget_code' => :'budget_code',
        :'medium' => :'medium',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'id' => :'Integer',
        :'parent_id' => :'Integer',
        :'campaign_type' => :'String',
        :'status' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'customer_information' => :'String',
        :'voucher_type' => :'String',
        :'max_total_budget' => :'Float',
        :'max_redemptions' => :'Float',
        :'minimum_value' => :'Float',
        :'maximum_value' => :'Float',
        :'discount_type' => :'String',
        :'discount_value' => :'Float',
        :'currency' => :'String',
        :'currency_symbol' => :'String',
        :'reward_title' => :'String',
        :'reward_value' => :'String',
        :'reward_description' => :'String',
        :'team' => :'String',
        :'channel' => :'String',
        :'purpose' => :'String',
        :'budget_code' => :'String',
        :'medium' => :'String',
        :'created_at' => :'DateTime',
        :'updated_at' => :'DateTime'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      end

      if attributes.has_key?(:'campaign_type')
        self.campaign_type = attributes[:'campaign_type']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'customer_information')
        self.customer_information = attributes[:'customer_information']
      end

      if attributes.has_key?(:'voucher_type')
        self.voucher_type = attributes[:'voucher_type']
      end

      if attributes.has_key?(:'max_total_budget')
        self.max_total_budget = attributes[:'max_total_budget']
      end

      if attributes.has_key?(:'max_redemptions')
        self.max_redemptions = attributes[:'max_redemptions']
      end

      if attributes.has_key?(:'minimum_value')
        self.minimum_value = attributes[:'minimum_value']
      end

      if attributes.has_key?(:'maximum_value')
        self.maximum_value = attributes[:'maximum_value']
      end

      if attributes.has_key?(:'discount_type')
        self.discount_type = attributes[:'discount_type']
      end

      if attributes.has_key?(:'discount_value')
        self.discount_value = attributes[:'discount_value']
      end

      if attributes.has_key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.has_key?(:'currency_symbol')
        self.currency_symbol = attributes[:'currency_symbol']
      end

      if attributes.has_key?(:'reward_title')
        self.reward_title = attributes[:'reward_title']
      end

      if attributes.has_key?(:'reward_value')
        self.reward_value = attributes[:'reward_value']
      end

      if attributes.has_key?(:'reward_description')
        self.reward_description = attributes[:'reward_description']
      end

      if attributes.has_key?(:'team')
        self.team = attributes[:'team']
      end

      if attributes.has_key?(:'channel')
        self.channel = attributes[:'channel']
      end

      if attributes.has_key?(:'purpose')
        self.purpose = attributes[:'purpose']
      end

      if attributes.has_key?(:'budget_code')
        self.budget_code = attributes[:'budget_code']
      end

      if attributes.has_key?(:'medium')
        self.medium = attributes[:'medium']
      end

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @parent_id.nil?
        invalid_properties.push('invalid value for "parent_id", parent_id cannot be nil.')
      end

      if @campaign_type.nil?
        invalid_properties.push('invalid value for "campaign_type", campaign_type cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      type_validator = EnumAttributeValidator.new('String', ['Campaign'])
      return false unless type_validator.valid?(@type)
      return false if @parent_id.nil?
      return false if @campaign_type.nil?
      campaign_type_validator = EnumAttributeValidator.new('String', ['discount'])
      return false unless campaign_type_validator.valid?(@campaign_type)
      status_validator = EnumAttributeValidator.new('String', ['draft', 'active', 'inactive'])
      return false unless status_validator.valid?(@status)
      return false if @name.nil?
      voucher_type_validator = EnumAttributeValidator.new('String', ['unique', 'generic'])
      return false unless voucher_type_validator.valid?(@voucher_type)
      discount_type_validator = EnumAttributeValidator.new('String', ['numeric', 'percentage'])
      return false unless discount_type_validator.valid?(@discount_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ['Campaign'])
      unless validator.valid?(type)
        fail ArgumentError, 'invalid value for "type", must be one of #{validator.allowable_values}.'
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] campaign_type Object to be assigned
    def campaign_type=(campaign_type)
      validator = EnumAttributeValidator.new('String', ['discount'])
      unless validator.valid?(campaign_type)
        fail ArgumentError, 'invalid value for "campaign_type", must be one of #{validator.allowable_values}.'
      end
      @campaign_type = campaign_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ['draft', 'active', 'inactive'])
      unless validator.valid?(status)
        fail ArgumentError, 'invalid value for "status", must be one of #{validator.allowable_values}.'
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] voucher_type Object to be assigned
    def voucher_type=(voucher_type)
      validator = EnumAttributeValidator.new('String', ['unique', 'generic'])
      unless validator.valid?(voucher_type)
        fail ArgumentError, 'invalid value for "voucher_type", must be one of #{validator.allowable_values}.'
      end
      @voucher_type = voucher_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] discount_type Object to be assigned
    def discount_type=(discount_type)
      validator = EnumAttributeValidator.new('String', ['numeric', 'percentage'])
      unless validator.valid?(discount_type)
        fail ArgumentError, 'invalid value for "discount_type", must be one of #{validator.allowable_values}.'
      end
      @discount_type = discount_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          id == o.id &&
          parent_id == o.parent_id &&
          campaign_type == o.campaign_type &&
          status == o.status &&
          name == o.name &&
          description == o.description &&
          customer_information == o.customer_information &&
          voucher_type == o.voucher_type &&
          max_total_budget == o.max_total_budget &&
          max_redemptions == o.max_redemptions &&
          minimum_value == o.minimum_value &&
          maximum_value == o.maximum_value &&
          discount_type == o.discount_type &&
          discount_value == o.discount_value &&
          currency == o.currency &&
          currency_symbol == o.currency_symbol &&
          reward_title == o.reward_title &&
          reward_value == o.reward_value &&
          reward_description == o.reward_description &&
          team == o.team &&
          channel == o.channel &&
          purpose == o.purpose &&
          budget_code == o.budget_code &&
          medium == o.medium &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [type, id, parent_id, campaign_type, status, name, description, customer_information, voucher_type, max_total_budget, max_redemptions, minimum_value, maximum_value, discount_type, discount_value, currency, currency_symbol, reward_title, reward_value, reward_description, team, channel, purpose, budget_code, medium, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Vouchery.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
