=begin
#Vouchery API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Vouchery::InlineObject3
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InlineObject3' do
  before do
    # run before each test
    @instance = Vouchery::InlineObject3.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineObject3' do
    it 'should create an instance of InlineObject3' do
      expect(@instance).to be_instance_of(Vouchery::InlineObject3)
    end
  end
  describe 'test attribute "file"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
