=begin
#Vouchery API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0
Contact: hello@vouchery.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

# Common files
require 'vouchery_client/api_client'
require 'vouchery_client/api_error'
require 'vouchery_client/version'
require 'vouchery_client/configuration'

# Models
require 'vouchery_client/models/batch'
require 'vouchery_client/models/campaign'
require 'vouchery_client/models/campaign_created_by'
require 'vouchery_client/models/category'
require 'vouchery_client/models/company'
require 'vouchery_client/models/customer'
require 'vouchery_client/models/customer_categories'
require 'vouchery_client/models/error'
require 'vouchery_client/models/error_errors'
require 'vouchery_client/models/inline_object'
require 'vouchery_client/models/inline_object1'
require 'vouchery_client/models/inline_object2'
require 'vouchery_client/models/inline_object3'
require 'vouchery_client/models/inline_object4'
require 'vouchery_client/models/inline_response200'
require 'vouchery_client/models/inline_response2001'
require 'vouchery_client/models/main_campaign'
require 'vouchery_client/models/main_campaign_children'
require 'vouchery_client/models/project'
require 'vouchery_client/models/redemption'
require 'vouchery_client/models/redemption_product_items'
require 'vouchery_client/models/redemption_voucher'
require 'vouchery_client/models/reward'
require 'vouchery_client/models/reward_add_points'
require 'vouchery_client/models/reward_assign_voucher'
require 'vouchery_client/models/reward_generate_product_item'
require 'vouchery_client/models/reward_generate_voucher'
require 'vouchery_client/models/reward_set_discount'
require 'vouchery_client/models/reward_set_discount_per_item'
require 'vouchery_client/models/rule'
require 'vouchery_client/models/rule_customer_category'
require 'vouchery_client/models/rule_customer_max_redemptions'
require 'vouchery_client/models/rule_customer_points'
require 'vouchery_client/models/rule_product_item_exists'
require 'vouchery_client/models/rule_product_item_exists_item_conditions'
require 'vouchery_client/models/rule_time_of_order'
require 'vouchery_client/models/rule_timeframe'
require 'vouchery_client/models/rule_triggers_amount'
require 'vouchery_client/models/trigger'
require 'vouchery_client/models/user'
require 'vouchery_client/models/voucher'

# APIs
require 'vouchery_client/api/campaigns_api'
require 'vouchery_client/api/categories_api'
require 'vouchery_client/api/company_api'
require 'vouchery_client/api/customers_api'
require 'vouchery_client/api/projects_api'
require 'vouchery_client/api/redemptions_api'
require 'vouchery_client/api/rewards_api'
require 'vouchery_client/api/rules_api'
require 'vouchery_client/api/triggers_api'
require 'vouchery_client/api/users_api'
require 'vouchery_client/api/vouchers_api'

module Vouchery
  class << self
    # Customize default settings for the SDK using block.
    #   Vouchery.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
